-- Creates a small table with three values

USE itmt430;

CREATE TABLE IF NOT EXISTS post 
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PosterName VARCHAR(32),
Title VARCHAR(32),
Content VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS account 
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
fName VARCHAR(50) NOT NULL,
lName VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL,
Phone VARCHAR(20),
City VARCHAR(50),
State VARCHAR(50),
Zip VARCHAR(10),
Country VARCHAR(50),
Occupation VARCHAR(50)
);